namespace CudaSharp;

/// <summary>
/// NVIDIA Runtime Compilation (NVRTC) API.
/// </summary>
/// <remarks>
/// NVRTC compiles CUDA C++ source to PTX, CUBIN, LTO IR, or OptiX IR. Starting with CUDA
/// Toolkit 13.3, it also compiles CUDA Tile C++ kernels declared with <c>__tile_global__</c>
/// from <c>cuda_tile.h</c> to TileIR; <c>tileiras</c> then assembles TileIR to CUBIN.
/// </remarks>
/// <seealso href="https://docs.nvidia.com/cuda/nvrtc/index.html"/>
/// <seealso href="https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/understanding-cuda-programming-model.html#writing-tile-kernels"/>
#pragma warning disable IDE1006 // Naming Styles
public static partial class nvrtc
#pragma warning restore IDE1006 // Naming Styles
{
    static nvrtc()
    {
        DllResolver.Register();
    }

    const string LibName = nameof(nvrtc);

    // Error handling and version information

    /// <summary>
    /// Returns a string representation of the given error code.
    /// </summary>
    /// <param name="result">The error code.</param>
    /// <returns>A pointer to the error string.</returns>
    // NOTE: Error string is nothing more than the enum definition as string. No
    //       need here really.
    [LibraryImport(LibName)]
    public static partial IntPtr nvrtcGetErrorString(nvrtcResult result);

    /// <summary>
    /// Sets the output parameters major and minor to the NVRTC version number.
    /// </summary>
    /// <param name="major">Output major version.</param>
    /// <param name="minor">Output minor version.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcVersion(out int major, out int minor);

    /// <summary>
    /// Gets the number of supported architectures.
    /// </summary>
    /// <param name="numArchs">Output number of supported architectures.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetNumSupportedArchs(out int numArchs);

    /// <summary>
    /// Gets the supported architectures sorted in ascending order.
    /// </summary>
    /// <param name="supportedArchs">Output buffer for supported architectures.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetSupportedArchs(Span<int> supportedArchs);

    // Program creation and compilation

    /// <summary>
    /// Creates a program with the given source code.
    /// </summary>
    /// <param name="prog">Output program handle.</param>
    /// <param name="src">CUDA source code.</param>
    /// <param name="name">Name of the program (optional).</param>
    /// <param name="numHeaders">Number of headers.</param>
    /// <param name="headers">Header sources.</param>
    /// <param name="includeNames">Header include names.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcCreateProgram(out nvrtcProgram prog,
        string src, string name, int numHeaders,
        in ReadOnlySpan<string> headers, in ReadOnlySpan<string> includeNames);

    /// <summary>
    /// Destroys the program.
    /// </summary>
    /// <param name="prog">Program handle to destroy.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcDestroyProgram(ref nvrtcProgram prog);

    /// <summary>
    /// Compiles the program.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="numOptions">Number of options.</param>
    /// <param name="options">Compiler options.</param>
    /// <returns>NVRTC_SUCCESS or compilation error.</returns>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcCompileProgram(nvrtcProgram prog,
        int numOptions, in ReadOnlySpan<string> options);

    /// <summary>
    /// Compiles the program with raw UTF-8 option pointers.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="numOptions">Number of options.</param>
    /// <param name="options">Pointer to an array of UTF-8 string pointers.</param>
    /// <returns>NVRTC_SUCCESS or compilation error.</returns>
    [LibraryImport(LibName)]
    public static unsafe partial nvrtcResult nvrtcCompileProgram(
        nvrtcProgram prog,
        int numOptions,
        byte** options);

    /// <summary>
    /// Registers a callback that NVRTC invokes during compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="callback">Callback that can request cancellation.</param>
    /// <param name="userData">User data passed to the callback.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcSetFlowCallback(
        nvrtcProgram prog,
        nvrtcFlowCallback callback,
        IntPtr userData);

    // Generated code and intermediate representations

    /// <summary>
    /// Gets the size of the PTX generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ptxSizeRet">Output PTX size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPTXSize(nvrtcProgram prog, out nuint ptxSizeRet);

    /// <summary>
    /// Gets the PTX generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ptx">Buffer to store PTX.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPTX(nvrtcProgram prog, Span<byte> ptx);

    /// <summary>
    /// Gets the size of the CUBIN generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="cubinSizeRet">Output CUBIN size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetCUBINSize(nvrtcProgram prog, out nuint cubinSizeRet);

    /// <summary>
    /// Gets the CUBIN generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="cubin">Buffer to store CUBIN.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetCUBIN(nvrtcProgram prog, Span<byte> cubin);

    /// <summary>
    /// Gets the size of the LTO IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ltoIRSizeRet">Output LTO IR size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetLTOIRSize(nvrtcProgram prog, out nuint ltoIRSizeRet);

    /// <summary>
    /// Gets the LTO IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ltoIR">Buffer to store LTO IR.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetLTOIR(nvrtcProgram prog, Span<byte> ltoIR);

    /// <summary>
    /// Gets the size of the OptiX IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="optixIRSizeRet">Output OptiX IR size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetOptiXIRSize(nvrtcProgram prog, out nuint optixIRSizeRet);

    /// <summary>
    /// Gets the OptiX IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="optixIR">Buffer to store OptiX IR.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetOptiXIR(nvrtcProgram prog, Span<byte> optixIR);

    /// <summary>
    /// Gets the size of the TileIR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="tileIRSizeRet">Output TileIR size in bytes.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetTileIRSize(nvrtcProgram prog, out nuint tileIRSizeRet);

    /// <summary>
    /// Gets the TileIR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="tileIR">Buffer to store TileIR.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetTileIR(nvrtcProgram prog, Span<byte> tileIR);

    // Bundled headers

    /// <summary>
    /// Gets information about the CUDA headers bundled with NVRTC without extracting them.
    /// </summary>
    /// <param name="info">Output bundled-header metadata.</param>
    /// <param name="errorLog">Optional output pointer to a diagnostic string owned by NVRTC.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetBundledHeadersInfo(
        out nvrtcBundledHeadersInfo info,
        out IntPtr errorLog);

    /// <summary>
    /// Extracts the CUDA headers bundled with NVRTC to a directory.
    /// </summary>
    /// <param name="installPath">Directory in which to install the bundled headers.</param>
    /// <param name="flags">Installation behavior flags.</param>
    /// <param name="errorLog">Optional output pointer to a diagnostic string owned by NVRTC.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcInstallBundledHeaders(
        string installPath,
        nvrtcInstallHeadersFlags flags,
        out IntPtr errorLog);

    /// <summary>
    /// Removes CUDA headers previously installed by <see cref="nvrtcInstallBundledHeaders"/>.
    /// </summary>
    /// <param name="installPath">Directory containing the installed bundled headers.</param>
    /// <param name="errorLog">Optional output pointer to a diagnostic string owned by NVRTC.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcRemoveBundledHeaders(
        string installPath,
        out IntPtr errorLog);

    // Precompiled headers

    /// <summary>Gets the status of the preceding PCH creation attempt.</summary>
    /// <param name="prog">Program handle.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPCHCreateStatus(nvrtcProgram prog);

    /// <summary>Gets the current NVRTC PCH heap size.</summary>
    /// <param name="size">Output heap size in bytes.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPCHHeapSize(out nuint size);

    /// <summary>Sets the NVRTC PCH heap size.</summary>
    /// <param name="size">Heap size in bytes.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcSetPCHHeapSize(nuint size);

    /// <summary>Gets the PCH heap size required to compile a program.</summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="size">Output required heap size in bytes.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPCHHeapSizeRequired(
        nvrtcProgram prog,
        out nuint size);

    // Compilation diagnostics

    /// <summary>
    /// Gets the size of the compilation log.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="logSizeRet">Output log size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetProgramLogSize(nvrtcProgram prog, out nuint logSizeRet);

    /// <summary>
    /// Gets the compilation log.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="log">Buffer to store the log.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetProgramLog(nvrtcProgram prog, Span<byte> log);

    // Name expressions

    /// <summary>
    /// Notes the given name expression to be used in the name mangling of the generated PTX.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="name_expression">Name expression (e.g. "&amp;func").</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcAddNameExpression(nvrtcProgram prog, string name_expression);

    /// <summary>
    /// Gets the lowered (mangled) name for a name expression.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="name_expression">Name expression.</param>
    /// <param name="lowered_name">Output pointer to the lowered name.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcGetLoweredName(nvrtcProgram prog, string name_expression,
        out IntPtr lowered_name);
}
