namespace CudaSharp;

/// <summary>
/// NVIDIA Runtime Compilation (NVRTC) API.
/// </summary>
/// <seealso href="https://docs.nvidia.com/cuda/nvrtc/index.html"/>
#pragma warning disable IDE1006 // Naming Styles
public static partial class nvrtc
#pragma warning restore IDE1006 // Naming Styles
{
    static nvrtc()
    {
        DllResolver.Register();
    }

    const string LibName = nameof(nvrtc);

    /// <summary>
    /// Returns a string representation of the given error code.
    /// </summary>
    /// <param name="result">The error code.</param>
    /// <returns>A pointer to the error string.</returns>
    // NOTE: Error string is nothing more than the enum definition as string. No
    //       need here really.
    [LibraryImport(LibName)]
    public unsafe static partial IntPtr nvrtcGetErrorString(nvrtcResult result);

    /// <summary>
    /// Sets the output parameters major and minor to the NVRTC version number.
    /// </summary>
    /// <param name="major">Output major version.</param>
    /// <param name="minor">Output minor version.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcVersion(out int major, out int minor);

    /// <summary>
    /// Gets the number of supported architectures.
    /// </summary>
    /// <param name="numArchs">Output number of supported architectures.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetNumSupportedArchs(out int numArchs);

    /// <summary>
    /// Gets the supported architectures sorted in ascending order.
    /// </summary>
    /// <param name="supportedArchs">Output buffer for supported architectures.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetSupportedArchs(Span<int> supportedArchs);

    /// <summary>
    /// Creates a program with the given source code.
    /// </summary>
    /// <param name="prog">Output program handle.</param>
    /// <param name="src">CUDA source code.</param>
    /// <param name="name">Name of the program (optional).</param>
    /// <param name="numHeaders">Number of headers.</param>
    /// <param name="headers">Header sources.</param>
    /// <param name="includeNames">Header include names.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcCreateProgram(out nvrtcProgram prog,
        string src, string name, int numHeaders,
        in ReadOnlySpan<string> headers, in ReadOnlySpan<string> includeNames);

    /// <summary>
    /// Destroys the program.
    /// </summary>
    /// <param name="prog">Program handle to destroy.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcDestroyProgram(ref nvrtcProgram prog);

    /// <summary>
    /// Compiles the program.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="numOptions">Number of options.</param>
    /// <param name="options">Compiler options.</param>
    /// <returns>NVRTC_SUCCESS or compilation error.</returns>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcCompileProgram(nvrtcProgram prog,
        int numOptions, in ReadOnlySpan<string> options);

    /// <summary>
    /// Gets the size of the PTX generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ptxSizeRet">Output PTX size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPTXSize(nvrtcProgram prog, out nuint ptxSizeRet);

    /// <summary>
    /// Gets the PTX generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ptx">Buffer to store PTX.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetPTX(nvrtcProgram prog, Span<byte> ptx);

    /// <summary>
    /// Gets the size of the CUBIN generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="cubinSizeRet">Output CUBIN size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetCUBINSize(nvrtcProgram prog, out nuint cubinSizeRet);

    /// <summary>
    /// Gets the CUBIN generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="cubin">Buffer to store CUBIN.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetCUBIN(nvrtcProgram prog, Span<byte> cubin);

    /// <summary>
    /// Gets the size of the LTO IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ltoIRSizeRet">Output LTO IR size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetLTOIRSize(nvrtcProgram prog, out nuint ltoIRSizeRet);

    /// <summary>
    /// Gets the LTO IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="ltoIR">Buffer to store LTO IR.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetLTOIR(nvrtcProgram prog, Span<byte> ltoIR);

    /// <summary>
    /// Gets the size of the OptiX IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="optixIRSizeRet">Output OptiX IR size.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetOptiXIRSize(nvrtcProgram prog, out nuint optixIRSizeRet);

    /// <summary>
    /// Gets the OptiX IR generated by the previous compilation.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="optixIR">Buffer to store OptiX IR.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetOptiXIR(nvrtcProgram prog, Span<byte> optixIR);

    /// <summary>
    /// Gets the size of the compilation log.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="logSizeRet">Output log size.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcGetProgramLogSize(nvrtcProgram prog, out nuint logSizeRet);

    /// <summary>
    /// Gets the compilation log.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="log">Buffer to store the log.</param>
    [LibraryImport(LibName)]
    public static partial nvrtcResult nvrtcGetProgramLog(nvrtcProgram prog, Span<byte> log);

    /// <summary>
    /// Notes the given name expression to be used in the name mangling of the generated PTX.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="name_expression">Name expression (e.g. "&amp;func").</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcAddNameExpression(nvrtcProgram prog, string name_expression);

    /// <summary>
    /// Gets the lowered (mangled) name for a name expression.
    /// </summary>
    /// <param name="prog">Program handle.</param>
    /// <param name="name_expression">Name expression.</param>
    /// <param name="lowered_name">Output pointer to the lowered name.</param>
    [LibraryImport(LibName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nvrtcResult nvrtcGetLoweredName(nvrtcProgram prog, string name_expression,
        out IntPtr lowered_name);
}
